-- MySQL Script generated by MySQL Workbench
-- 07/06/14 11:04:44
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Colegio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Colegio` ;
CREATE SCHEMA IF NOT EXISTS `Colegio` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `Colegio` ;

-- -----------------------------------------------------
-- Table `Colegio`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Telefono` CHAR(9) NULL,
  `FechaNacimiento` DATE NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
COMMENT = '	';

CREATE UNIQUE INDEX `idAlumno_UNIQUE` ON `Colegio`.`Alumno` (`idAlumno` ASC);


-- -----------------------------------------------------
-- Table `Colegio`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `Grado` VARCHAR(5) NOT NULL,
  `Seccion` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `CantidadNotas` INT NULL DEFAULT 0,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  CONSTRAINT `fk_Curso_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `Colegio`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_Grupo1_idx` ON `Colegio`.`Curso` (`Grupo_idGrupo` ASC);


-- -----------------------------------------------------
-- Table `Colegio`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Notas` (
  `idNotas` INT NOT NULL AUTO_INCREMENT,
  `Nota` DECIMAL(2,2) NOT NULL,
  `Alumno_idAlumno` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idNotas`, `Alumno_idAlumno`, `Curso_idCurso`),
  CONSTRAINT `fk_Notas_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `Colegio`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Colegio`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Notas_Alumno1_idx` ON `Colegio`.`Notas` (`Alumno_idAlumno` ASC);

CREATE INDEX `fk_Notas_Curso1_idx` ON `Colegio`.`Notas` (`Curso_idCurso` ASC);


-- -----------------------------------------------------
-- Table `Colegio`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Telefono` CHAR(9) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Colegio`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `Alumno_idAlumno` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Dia` DATETIME NOT NULL,
  PRIMARY KEY (`idAsistencia`, `Alumno_idAlumno`, `Curso_idCurso`),
  CONSTRAINT `fk_Asistencia_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `Colegio`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Colegio`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Asistencia_Alumno1_idx` ON `Colegio`.`Asistencia` (`Alumno_idAlumno` ASC);

CREATE INDEX `fk_Asistencia_Curso1_idx` ON `Colegio`.`Asistencia` (`Curso_idCurso` ASC);


-- -----------------------------------------------------
-- Table `Colegio`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `HoraInicio` DATETIME NOT NULL,
  `HoraFin` DATETIME NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  CONSTRAINT `fk_Horario_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `Colegio`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `Colegio`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Horario_Curso1_idx` ON `Colegio`.`Horario` (`Curso_idCurso` ASC);

CREATE INDEX `fk_Horario_Profesor1_idx` ON `Colegio`.`Horario` (`Profesor_idProfesor` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
